---

- name: Deploy master DB
  hosts: masterDB_server
  become: yes

  roles:
    - role: deploy_DBmaster
      when: "ansible_facts['os_family'] == 'RedHat'"

- name: Deploy slave DB
  hosts: slaveDB_server
  become: yes

  roles:
    - role: deploy_DBslave
      when: "ansible_facts['os_family'] == 'RedHat'"

- name: Deploy backend server1
  hosts: backend_server1
  become: yes

  roles:
    - role: deploy_backend_server1
      when: "ansible_facts['os_family'] == 'RedHat'"

- name: Deploy backend server2
  hosts: backend_server2
  become: yes

  roles:
    - role: deploy_backend_server2
      when: "ansible_facts['os_family'] == 'RedHat'"